# Generated by Django 5.0.7 on 2024-11-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
